services:
  ampa-app:
    ports:
      - "8008:8008"
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SERVER=${SERVER}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - PYTHONPATH=/app
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    build: .
    volumes:
      - ./:/app
    networks:
      - db_network
      - web_network
      - django_network
networks:
  db_network:
  web_network:
  django_network:
